# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr:
  branches:
    include:
    - dev

stages:
- stage: Main
  jobs:
  - job: Ubuntu_latest
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 0
    variables:
      COMPILER_CC: gcc-7
      COMPILER_CXX: g++-7
      COMPILER_FC: gfortran-7
      BUILD_SHARED_LIBS: ON
      CMAKE_BUILD_TYPE: Debug
    steps:
      - checkout: self
        clean: boolean

      - script: |
           #################################
           # build spack dependencies
           #################################
           export ROOT_DIR=$(pwd)
           echo "ROOT_DIR:" ${ROOT_DIR}
           wget https://github.com/spack/spack/archive/v0.14.0.tar.gz
           tar -xzf v0.14.0.tar.gz
           mv spack-0.14.0 spack
           export PATH=${ROOT_DIR}/spack/bin:${PATH}

           spack mirror add local_filesystem file://${ROOT_DIR}/scripts/travis/mirrors
           ls ${ROOT_DIR}/scripts/travis/mirrors

           # hwloc
           spack install hwloc
           export HWLOC_DIR=`ls -d ${ROOT_DIR}/spack/opt/spack/*/*/hwloc-*`
           echo -e "HWLOC_DIR:" ${HWLOC_DIR}
        displayName: 'Spack Build Dependencies'

      - script: |
           #################################
           # configure
           #################################
           # setup compiler env vars
           export CC=${COMPILER_CC}
           export CXX=${COMPILER_CXX}
           export FC=${COMPILER_FC}
           ${CC} --version
           # capture current path
           export ROOT_DIR=$(pwd)
           which cmake
           cmake --version
           # prepare build dir
           mkdir build
           cd build
           # setup cmake options
           export CMAKE_OPTS="-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}"
           export CMAKE_OPTS="${CMAKE_OPTS} -DCMAKE_INSTALL_PREFIX=../install"
           # configure
           cmake ${CMAKE_OPTS} ../src
        displayName: 'Configure with CMake'
