stages:
  - status_initiate
  - build
  - status_update

.on_catalyst:
  tags:
    - shell
    - catalyst
  rules:
    # Only report failure if the pipeline failed.
    - if: '$CI_JOB_NAME =~ /status_failure/'
      when: on_failure
    # A true statement is expected to allow jobs to run. Here is the default.
    - when: on_success

.status_report: &status_report
    - export context="catalyst"
    - |
      curl --url "https://api.github.com/repos/llnl/${CI_PROJECT_NAME}/statuses/${CI_COMMIT_SHA}" \
           --header 'Content-Type: application/json' \
           --header "authorization: Bearer ${GITHUB_TOKEN}" \
           --data "{ \"state\": \"${pipeline_status}\", \"target_url\": \"${CI_PIPELINE_URL}\", \"description\": \"GitLab ${context} pipeline\", \"context\": \"ci/gitlab/${context}\" }"

status_pending:
  extends: [.on_catalyst]
  stage: status_initiate
  script:
    - export pipeline_status="pending"
    - *status_report

status_success:
  extends: [.on_catalyst]
  stage: status_update
  script:
    - export pipeline_status="success"
    - *status_report
  when: on_success

status_failure:
  extends: [.on_catalyst]
  stage: status_update
  script:
    - export pipeline_status="failure"
    - *status_report
  when: on_failure

# no access to msr-safe on catalyst
build-catalyst:
 tags:
   - batch
   - catalyst
 stage: build
 script:
   # Build and install rankstr dependency
   - git clone https://github.com/ECP-VeloC/rankstr.git
   - cd rankstr
   - mkdir build install && cd build
   - cmake -DCMAKE_INSTALL_PREFIX=../install ..
   - VERBOSE=1 make -j
   - make install
   - RANKSTR_INSTALL=${PWD}/../install
   - cd ../../
   - export HOSTNAME=`hostname`
   - echo -e "Hostname:" ${HOSTNAME}
   - groups
   - mkdir build-gitlab-catalyst && mkdir install-gitlab-catalyst
   - cd build-gitlab-catalyst
   - export HOST_CONFIG=`ls ../host-configs/catalyst-toss_3_x86_64_ib-gcc@8.3.1.cmake`
   - echo -e "HOST_CONFIG:" ${HOST_CONFIG}
   - echo -e "PWD:" ${PWD}
   - cmake -C ${HOST_CONFIG} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../install-gitlab-catalyst -DBUILD_TESTS=ON -DENABLE_WARNINGS=ON -DRANKSTR_DIR=${RANKSTR_INSTALL} ../src
   - make VERBOSE=1
   - make install
   #- env CTEST_OUTPUT_ON_FAILURE=1 make test
   - cd ..
   - echo -e "PWD:" ${PWD}
   - which cmake
   - cmake --version
   - cd install-gitlab-catalyst/examples/using-with-cmake/c
   - echo -e "PWD:" ${PWD}
   - mkdir _test_build
   - cd _test_build
   - cmake ../
   - make VERBOSE=1
   #- ./variorum-print-power-example
   - cd ../../../using-with-make/c
   - echo -e "PWD:" ${PWD}
   - make VERBOSE=1
   #- ./variorum-print-power-example
   - cd ../../using-with-make/cpp
   - echo -e "PWD:" ${PWD}
   - make VERBOSE=1
   #- ./variorum-print-power-example
   - cd ../../using-with-make/fortran
   - echo -e "PWD:" ${PWD}
   - make VERBOSE=1 F77=/usr/tce/packages/gcc/gcc-8.3.1/bin/gfortran FFLAGS=-O
   #- ./ep.W.x
